version: '3.8'

services:
  db_argentina:
    image: postgres:18
    container_name: postgres_tp_arg
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: superpassword123
      POSTGRES_DB: tp_datos_argentina
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d  

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_tp_arg
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: grupo@utn.edu.ar
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db_argentina
volumes:
  postgres_data: